### ISSUE TITLE
Provide a license file

### ISSUE THREAD

**Issue by SISheogorath** [slauger/hcloud-okd4#159]
It seems that part of the idea of this repository is to be able to learn and extend from it. Therefore it would be nice, if it would provide a license file, so it's clear what to expect from the repository.

For example, I for myself love to mirror useful repository and currently look into this repository to make extend it with hcloud firewall rules and alike, which I would love to contribute back. But for now, I can't do anything with it, without a license. :/

**Comment by slauger** [comment]
Hi,

> It seems that part of the idea of this repository is to be able to learn and extend from it.

Yes, absolutely! I really appreciate any kind of contribution/feedback to this repo.

Sorry, i thought that it is well known that OKD requires a fake pull secret. Just use

```
{"auths":{"fake":{"auth": "bar"}}}
```

You can also get a trial license for OCP via cloud.openshift.com. It is not required, but allows you to install OCP4 operators on OKD4 or (obviously) install OCP. This should also work with the free RedHat developer account.

**Comment by SISheogorath** [comment]
Oh, I meant a License file, like GPL or MIT for this repository 😅  I'm aware about the license situation with OKD and OCP.

**Comment by slauger** [comment]
Oh, sorry. You're right. I'll add a MIT license file in a bit.

**Comment by slauger** [comment]
Fixed! Awaiting your feedback. I haven't had much time to work on this repo in the past few weeks.
