### ISSUE TITLE
packer does not deploy authorized_keys to image

### ISSUE THREAD

**Issue by oliverrahner** [slauger/hcloud-okd4#187]
When calling `make infrastructure BOOTSTRAP=true`, the machines `bootstrap01`, `ignition01` and `master01` are being created.

After waiting for the SSH connection to be available, the SSH connection fails with `Permission denied (publickey)`.

After investigating, I couldn't find any place where the SSH key would be set in the base image by packer during `make hcloud_image`.

Can anybody tell me what I am missing?

**Comment by oliverrahner** [comment]
One step further:
I found that `http://169.254.169.254/hetzner/v1/userdata` should return in some form the public keys set up in the hcloud project. But that endpoint does not return anything for me, only HTTP 200 with `Content-Length: 0`.
http://169.254.169.254/hetzner/v1/**metadata** works though...

**Comment by slauger** [comment]
Hi,

your ssh key is not part of the terraform manifests. The key is defined in the ignition config, generated by the openshift-install cli command. It is defined in your install-config.yaml. How does your install-config.yaml look like? Are you using the core user for the SSH connection?

An exception is the ignition host btw. This machine will receive all ssh keys in your project (via terraform).

**Comment by oliverrahner** [comment]
My install-config.yaml has the public key which is the identity of the user running `make run`, so as I understood the tool chain, that should be correct.
The ignition host is the one with the problem.

If I got it correctly, then the following part of `packer/config-3.0.0.ign` should be the one which is responsible, among other things, for settings the correct SSH keys:
```
    "config": {
      "merge": [
        {
          "source": "http://169.254.169.254/hetzner/v1/metadata",
          "verification": {}
        }
      ]
    },
```

But as mentioned, the answer received from the `source` endpoint is empty.

**Comment by oliverrahner** [comment]
So without any mention of the `userdata` endpoint in Hetzner's docs, it seems that this endpoint contains exactly what has been set as "user data" during server creation.
But I didn't find any mention as to what it is supposed to be set to?

**Comment by oliverrahner** [comment]
Sorry for all the confusion, I cleaned my "thinking notes" up :)

I think I got it now:
`userdata` is empty, as it is can only be seen _inside_ the machines deployed by Terraform.

My problem seems to be that I created a separate ssh identity on my first, dedicated management machine, the public key of which was **not** set up in the Hetzner Cloud Console.
