### ISSUE TITLE
packer builder missing

### ISSUE THREAD

**Issue by ebartz** [slauger/hcloud-okd4#311]
When building the hcloud image, the following issue comes up:

```
make hcloud_image
if [ "okd" == "okd" ]; then (cd packer && packer build -var fcos_url=https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20221127.3.0/x86_64/fedora-coreos-37.20221127.3.0-qemu.x86_64.qcow2.xz hcloud-fcos.json); fi
Error: Failed to initialize build "hcloud"

error initializing builder 'hcloud': Unknown builder hcloud


make: *** [Makefile:89: hcloud_image] Error 1
```

To fix this, you need to install the plugin first:

```
packer plugins install github.com/hashicorp/hcloud
```

Question: @slauger should this be part of the dockerfile, or part of the makefile?

**Comment by slauger** [comment]
Hi Enrico,

thanks for your hint. I've already stumbled across this packer change with a different image build pipeline.

The hcloud plugin for packer should be installed in the Dockerfile during build time. Feel free to provide a merge request. If not i will maybe have time for it in the evening.
