### ISSUE TITLE
make toolbox not working (anymore?)

### ISSUE THREAD

**Issue by NicoWde** [slauger/hcloud-okd4#33]
Hello,

first: thank you for opening up your archivements to the world! 👍 

I just cloned this repo and started from scratch (as written in readme), and on the second command "make toolbox" I got following error:
````
[root@void hcloud-okd4]# make toolbox
make: *** Keine Regel, um „toolbox“ zu erstellen.  Schluss.
````

I'd guess it is just not there anymore.

Kind Regards,
Nico

**Comment by timbrd** [comment]
> Hello,
> 
> first: thank you for opening up your archivements to the world! 👍
> 
> I just cloned this repo and started from scratch (as written in readme), and on the second command "make toolbox" I got following error:
> 
> ```
> [root@void hcloud-okd4]# make toolbox
> make: *** Keine Regel, um „toolbox“ zu erstellen.  Schluss.
> ```
> 
> I'd guess it is just not there anymore.
> 
> Kind Regards,
> Nico

You can build the toolbox image with `make build`. I think @slauger just forgot to update the documentation after changing the Makefile target.

**Comment by NicoWde** [comment]
thanks for the note :) 

than my issue is an outdated ReadMe..

**Comment by slauger** [comment]
Hi,

> I think @slauger just forgot to update the documentation after changing the Makefile target.

exactly - `make build` is what you are searching for. I already fixed the README.md. ;)

I would appreciate your feedback!
