### ISSUE TITLE
make wait_bootstrap fails: FATAL loading kubeconfig

### ISSUE THREAD

**Issue by NicoWde** [slauger/hcloud-okd4#34]
Hello @slauger,

thanks again for creating this! (And fixing the docs, great work!)

I found another issue.

On current master, there the Makefile instructs "wait_bootstrap" to:
````
wait_bootstrap:
        openshift-install --dir=config/ wait-for bootstrap-complete --log-level=debug
````

kubeconf is saved in ignition.

I'd probably open a PR later this day, but for now, locally fixed "--dir=config/" to "--dir=ignition/", which works totally fine.

Thanks again for your great work!

Kind Regards,
Nico

**Comment by NicoWde** [comment]
probably it's the same situation with "make manifests" and "make wait_completion".

**Comment by slauger** [comment]
The kubeconfig should be be copied to the `config` directory during the `manifests` target.

```
manifests:
	mkdir config
	cp install-config.yaml config/install-config.yaml
	openshift-install create manifests --dir=config
	cp -r ignition/auth config/auth
```

**Comment by NicoWde** [comment]
oh... damn. sorry about that! Maybe I should have checked that.

**Comment by slauger** [comment]
No problem! Just let me know if you need any further help. 👍
