### ISSUE TITLE
What content should be found at this URL?

### ISSUE THREAD

**Issue by tstec-polypoly** [slauger/hcloud-okd4#48]
What content should be found at this URL?
https://github.com/slauger/hcloud-okd4/blob/f4493ba5964d09cd961ed97f4f41ab2a300972b7/packer/config.ign#L6

**Comment by tstec-polypoly** [comment]
The one from `make generate_ignition` ?

**Comment by slauger** [comment]
This is the URL of the hcloud user data, where we put in the rendered `template.ign` from the terraform hcloud_coreos module. This template basically contains another `source` statement - to either the ignition node (for the bootstrap node) or directly machine config server (`api-int:22623`).

https://github.com/slauger/hcloud-okd4/blob/master/terraform/modules/hcloud_coreos/main.tf#L8
https://github.com/slauger/hcloud-okd4/blob/master/terraform/modules/hcloud_coreos/template.ign

The field is limited to 32KiB. The ignition file for the bootstrap node exceeds the limit of 32KiB, so we need the "workaround" with the ignition node.

**Comment by tstec-polypoly** [comment]
Thanks for the quick response!
